/**
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */
export default {
  app: { title: 'Ads Platform', copyright: 'Copyright (c) 2026 erik' },
  nav: { dashboard: 'Dashboard', campaigns: 'Campaigns', accounts: 'Accounts', reports: 'Reports', alerts: 'Alerts', alertRules: 'Alert Rules', alertLogs: 'Alert Logs', reportExport: 'Export', system: 'System', userManage: 'Users', auditLog: 'Audit Log', apiDocs: 'API Docs' },
  login: { title: 'Ads Platform', username: 'Username', password: 'Password', login: 'Login', usernameRequired: 'Username is required', passwordRequired: 'Password is required' },
  dashboard: { title: 'Dashboard', todayCost: 'Today Cost', impressions: 'Impressions', clicks: 'Clicks', ctr: 'CTR', cvr: 'CVR', avgCpa: 'Avg CPA', platformCost: 'Cost by Platform', topCampaigns: 'Top 10 Campaigns', trend: 'Cost Trend', exportPdf: 'Export PDF', exportExcel: 'Export Excel', last7days: 'Last 7 Days', last30days: 'Last 30 Days', today: 'Today', yesterday: 'Yesterday', vsYesterday: 'vs Yesterday' },
  campaign: { title: 'Campaigns', create: 'Create Campaign', edit: 'Edit Campaign', name: 'Campaign Name', platform: 'Platform', account: 'Account', dailyBudget: 'Daily Budget', status: 'Status', enabled: 'Active', paused: 'Paused', deleted: 'Deleted', todayCost: 'Today Cost', actions: 'Actions', toggleOn: 'Enable', toggleOff: 'Pause', batchToggle: 'Batch Toggle', batchEnabled: 'Batch Enable', batchDisabled: 'Batch Pause', selected: '{count} selected', search: 'Search campaigns', allPlatforms: 'All Platforms', allStatus: 'All Status', cancel: 'Cancel', confirm: 'Confirm', createSuccess: 'Created successfully', updateSuccess: 'Updated successfully', toggleSuccess: '{action}' },
  account: { title: 'Accounts', bind: 'Bind Account', platform: 'Platform', accountName: 'Account Name', platformAccountId: 'Platform ID', status: 'Status', lastSync: 'Last Sync', actions: 'Actions', sync: 'Sync', unbind: 'Unbind', normal: 'Normal', disabled: 'Disabled', notSynced: 'Not Synced', syncTriggered: 'Sync triggered', unbindConfirm: 'Unbind this account?', unbindSuccess: 'Unbound', bindTitle: 'Bind Platform Account', selectPlatform: 'Select Platform', authorizeLogin: 'Authorize', complete: 'Complete', next: 'Next', goAuth: 'Authorize', callbackUrl: 'Callback URL', bindSuccess: 'Bound Successfully', viewAccounts: 'View Accounts', continueBind: 'Continue Binding' },
  report: { title: 'Custom Report', export: 'Export', format: 'Format', csv: 'CSV', excel: 'Excel', dashboardPdf: 'Dashboard PDF', dimensions: 'Dimensions', metrics: 'Metrics', dateRange: 'Date Range', platform: 'Platform', startDate: 'Start Date', endDate: 'End Date', exportReport: 'Export Report', cost: 'Cost', impressions: 'Impressions', clicks: 'Clicks', conversions: 'Conversions', roi: 'ROI', cpc: 'CPC', cpm: 'CPM' },
  alert: { rules: 'Alert Rules', logs: 'Alert Logs', createRule: 'Create Rule', editRule: 'Edit Rule', ruleName: 'Rule Name', metric: 'Metric', condition: 'Condition', threshold: 'Threshold', scope: 'Scope', channels: 'Channels', checkInterval: 'Interval(min)', status: 'Status', enabled: 'Enabled', disabled: 'Disabled', triggered: 'Triggered', acknowledged: 'Acknowledged', resolved: 'Resolved', acknowledge: 'Acknowledge', unreadCount: 'Unread', allStatus: 'All Status', web: 'Web', email: 'Email', sms: 'SMS', tenant: 'Tenant', byPlatform: 'By Platform', byCampaign: 'By Campaign' },
  system: { userManage: 'User Management', auditLog: 'Audit Log', username: 'Username', name: 'Name', email: 'Email', role: 'Role', lastLogin: 'Last Login', actions: 'Actions', edit: 'Edit', disable: 'Disable', createUser: 'Create User', editUser: 'Edit User', password: 'Password', passwordOptional: 'Password (leave blank unchanged)', operator: 'Operator', action: 'Action', resource: 'Resource', resourceId: 'Resource ID', detail: 'Detail', ip: 'IP Address', time: 'Time' },
  common: { save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete', edit: 'Edit', search: 'Search', reset: 'Reset', loading: 'Loading...', noData: 'No Data', total: '{total} total', page: 'Page {page}', export: 'Export', refresh: 'Refresh', back: 'Back', logout: 'Logout', yes: 'Yes', no: 'No', success: 'Success', error: 'Error', networkError: 'Network Error', confirmDelete: 'Confirm delete?', yuan: '¥', fen: 'fen' },
  confirm: { typeConfirm: 'Type {word} to confirm', title: 'Confirm Action' },
  captcha: { title: 'Security Check', slideHint: 'Slide to verify', success: 'Verified', failed: 'Verification failed', required: 'Please complete verification' },
  time: { minute: 'min', hour: 'hour', day: 'day' },
  metric: { cost: 'Cost', impressions: 'Impressions', clicks: 'Clicks', conversions: 'Conversions', ctr: 'CTR', cvr: 'CVR', roi: 'ROI' },
  condition: { gt: 'greater than', gte: 'greater or equal', lt: 'less than', lte: 'less or equal' },
}
